import type { DragEvent, FormEvent } from 'react'
import { ArrowRight, FolderOpen, Mic, MicOff, Paperclip, Pencil, Square, X } from 'lucide-react'
import { fileDisplayName, fileIdentity, getFileIcon } from '../../../utils/documents'
import { formatBytes } from '../../../utils/formatters'

type AnalysisRequestPanelProps = {
  pendingFiles: File[]; prompt: string; isLoading: boolean; isListening: boolean; editingMessageId: string | null; isDragging: boolean
  setPrompt: (value: string) => void; setIsDragging: (value: boolean) => void; handleDrop: (event: DragEvent<HTMLDivElement>) => void; submitPrompt: (event: FormEvent) => void; stopGeneration: () => void; cancelEdit: () => void; toggleVoiceInput: () => void; removePending: (file: File) => void; openFiles: () => void; openFolder: () => void
}

export function ChatComposer(props: AnalysisRequestPanelProps) {
  return (
    <div className="pointer-events-none absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#fffdf8] via-[#fffdf8] to-transparent px-4 pb-4 pt-12 sm:px-7 sm:pb-6">
      <form onSubmit={props.submitPrompt} className="pointer-events-auto mx-auto w-full max-w-[920px]">
        <div className={`overflow-visible rounded-2xl border bg-[#fffefa] shadow-[0_16px_42px_rgba(91,61,25,0.14)] transition ${props.isDragging ? 'border-[#c88a2e] ring-4 ring-[#f3dfbb]' : 'border-[#e4d5bd]'}`} onDragEnter={(event) => { event.preventDefault(); props.setIsDragging(true) }} onDragOver={(event) => event.preventDefault()} onDragLeave={() => props.setIsDragging(false)} onDrop={props.handleDrop}>
          <div className="flex items-center justify-between border-b border-[#eee3d2] px-4 py-2.5"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#9a6725]">Analysis request</p><p className="mt-0.5 text-[10px] text-[#8d7b62]">Add your source material and define the outcome you need.</p></div>{props.pendingFiles.length > 0 && <span className="rounded-full bg-[#f2dfbd] px-2.5 py-1 text-[10px] font-bold text-[#8d5d1e]">{props.pendingFiles.length} source{props.pendingFiles.length === 1 ? '' : 's'} ready</span>}</div>
          {props.editingMessageId && <div className="flex items-center gap-2 border-b border-[#ead9be] bg-[#fff7e9] px-4 py-2 text-[10px] font-semibold text-[#795729]"><Pencil size={13} />Editing request. Running again replaces later report content.<button type="button" className="ml-auto rounded-md p-1 hover:bg-[#f1dfc1]" aria-label="Cancel edit" onClick={props.cancelEdit}><X size={13} /></button></div>}
          {props.pendingFiles.length > 0 && <div className="flex gap-2 overflow-x-auto border-b border-[#eee3d2] px-3 py-3">{props.pendingFiles.map((file) => { const Icon = getFileIcon(file.name); return <div key={fileIdentity(file)} className="attachment-chip"><div className="file-icon h-8 w-8"><Icon size={15} /></div><div className="min-w-0"><div className="truncate text-[11px] font-semibold" title={fileDisplayName(file)}>{fileDisplayName(file)}</div><div className="text-[9px] text-[#9b8a72]">{formatBytes(file.size)}</div></div><button type="button" aria-label={`Remove ${file.name}`} onClick={() => props.removePending(file)}><X size={13} /></button></div> })}</div>}
          {props.isDragging ? <div className="grid h-[116px] place-items-center text-sm font-semibold text-[#9c6421]">Drop source material here</div> : <><textarea value={props.prompt} onChange={(event) => props.setPrompt(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); event.currentTarget.form?.requestSubmit() } }} className="min-h-[88px] w-full resize-none border-0 bg-transparent px-4 py-4 text-sm leading-6 text-[#4e4234] outline-none placeholder:text-[#a99983]" placeholder="Describe the report you need — e.g. executive summary, key risks, comparison, or extracted data." aria-label="Analysis prompt" />
            <div className="flex items-center gap-1.5 border-t border-[#eee3d2] px-3 py-3"><button type="button" className="composer-button" onClick={props.openFiles}><Paperclip size={16} /><span className="hidden sm:inline">Add files</span></button><button type="button" className="composer-button" onClick={props.openFolder}><FolderOpen size={16} /><span className="hidden sm:inline">Add folder</span></button><button type="button" className={`composer-button ${props.isListening ? 'voice-button-active' : ''}`} aria-label={props.isListening ? 'Stop voice input' : 'Start voice input'} onClick={props.toggleVoiceInput}>{props.isListening ? <MicOff size={16} /> : <Mic size={16} />}<span className="hidden md:inline">{props.isListening ? 'Listening…' : 'Voice note'}</span></button><div className="ml-auto">{props.isLoading ? <button type="button" aria-label="Stop analysis" className="stop-button" onClick={props.stopGeneration}><Square size={14} fill="currentColor" /></button> : <button type="submit" disabled={!props.prompt.trim()} className="flex h-9 items-center gap-2 rounded-lg bg-[#d99a36] px-3 text-[11px] font-bold text-[#2d1d0c] transition hover:bg-[#e7aa43] disabled:bg-[#ded5c8] disabled:text-[#9a8d7c]"><span className="hidden sm:inline">Run analysis</span><ArrowRight size={16} /></button>}</div></div></>}
        </div>
        <p className="mt-2 text-center text-[9px] text-[#a39582]">Review generated findings against the original source material before making decisions.</p>
      </form>
    </div>
  )
}
